# Generated by Django 3.1.1 on 2021-05-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210512_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricbill',
            options={'ordering': ['-date']},
        ),
    ]
