# Generated by Django 3.1.1 on 2021-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210518_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
