# Generated by Django 3.1.1 on 2021-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('medicine_name', models.CharField(max_length=100, null=True)),
                ('medical_name', models.CharField(max_length=100, null=True)),
                ('medicine_type', models.CharField(max_length=20, null=True)),
                ('medicine_size', models.IntegerField()),
                ('metric', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
