# Generated by Django 3.1.1 on 2021-04-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='medicine_size',
        ),
        migrations.RemoveField(
            model_name='category',
            name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='metric',
        ),
    ]
