# Generated by Django 3.1.1 on 2021-04-24 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20210424_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='adding_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='quantitiy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_price_with_discount',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_price_without_discount',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
