# Generated by Django 3.1.1 on 2021-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20210424_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='adding_date',
            field=models.DateTimeField(null=True),
        ),
    ]
