# Generated by Django 3.1.1 on 2021-04-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20210424_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
