# Generated by Django 3.1.1 on 2021-04-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20210425_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='quantity',
            new_name='qty',
        ),
    ]
