# Generated by Django 3.1.1 on 2021-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20210425_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cost_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cost_without_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, null=True),
        ),
    ]
