# Generated by Django 3.1.1 on 2021-04-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20210425_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
