# Generated by Django 3.1.1 on 2021-04-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20210425_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sold_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='sold_qty',
            field=models.IntegerField(default=0),
        ),
    ]
