# Generated by Django 3.1.1 on 2021-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_remove_category_adding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SellingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sold_amount',
            new_name='sold_price',
        ),
    ]
