# Generated by Django 3.1.1 on 2021-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_auto_20210501_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinfo',
            old_name='price',
            new_name='cost_with_discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cost_with_discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cost_without_discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sold_qty',
        ),
        migrations.RemoveField(
            model_name='category',
            name='unit_price_with_discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='unit_price_without_discount',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sellinginfo',
            name='profit',
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='cost_without_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='unit_price_with_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='purchaseinfo',
            name='unit_price_without_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
