# Generated by Django 3.1.1 on 2021-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_auto_20210501_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sellinginfo',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
