# Generated by Django 3.1.1 on 2021-05-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_auto_20210501_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='cost_with_discount',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='unit_price_with_discount',
        ),
        migrations.RemoveField(
            model_name='purchaseinfo',
            name='unit_price_without_discount',
        ),
    ]
