# Generated by Django 3.1.1 on 2021-05-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0018_auto_20210501_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinginfo',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellinginfo',
            name='customer_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
