# Generated by Django 3.1.1 on 2021-05-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0019_auto_20210501_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('selling_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
    ]
