# Generated by Django 3.1.1 on 2021-05-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0020_profitinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellingInfo',
        ),
    ]
