# Generated by Django 3.1.1 on 2021-05-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0021_delete_sellinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
