# Generated by Django 3.1.1 on 2021-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0023_auto_20210508_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
